### ISSUE TITLE
'Item "{id}" could not be added to cart.'

### ISSUE THREAD

**Issue by plagasul** [wagnerwagner/merx#33]
Hello,

I am getting the exception `'Item "{id}" could not be added to cart.'` when trying to add certain products to the cart.

Contrary to regular products, which I can add without problems, these products sit in a subpage

```
content
  product A
  product B
  ...
  frame-options
    frame-product A
    frame-product B
```

These frame-products also have a different blueprint from regular products,`frame-product.yml` which goes like this:

```
title: Frame Product
icon: box

options:
  changeTitle: true
  changeStatus: true
  changeTemplate: false
  changeSlug: true
  delete: true

fields:
  price:
    label: Price
    type: number
    step: ,01
    width: 1/4
    placeholder: 0,00
    after: €
  width:
    label: Width
    type: number
    width: 1/4
    placeholder: 21
    after: cm
  height:
    label: Height
    type: number
    width: 1/4
    placeholder: 30
    after: cm
  passepartout:
    label: Passepartout?
    type: toggle
    text:
      - 'no'
      - 'yes'
    width: 1/4
    default: 'no'
```

This is an example .txt file of such product:

```
Title: Wood, white

----

Price: 20

----

Width: 21

----

Height: 30

----

Passepartout: true
```

The code that triggers the exception is simply:

```
cart()->add([
  'id' => 'wood-white'
]);
```

Which works fine by susbstituting the id by that of a regular product, such as `'cactus'`.

As I am not getting `'No "id" is provided.'` , `'Page not found.'` or `'Page must have a price field.'` I assume those are not the issues here (shouldn't be nevertheless). 

So ¿what could be the issue?

Danke
